Repository LLK/scratch-render, pull requests merged in 2018-05, with the labels that each got.

#268 Scale the drawable scale by the ratio of pixel size to native size.
  src/RenderWebGL.js
Labels: pr - needs review

#267 Fix color inversion bug on mobile
  src/shaders/sprite.frag
Labels: pr - needs review

#270 Update to webpack 4
  package.json
  webpack.config.js
Labels: pr - good to merge

#271 Replace babel-preset-es2015 with babel-preset-env
  package.json
  webpack.config.js
Labels: pr - good to merge

#286 Remove speech bubbles' reliance on svg quirks mode's _transformText
  src/Silhouette.js
  src/util/svg-text-bubble.js
  src/util/svg-text-wrapper.js
Labels: pr - good to merge

#288 Publish only src, dist, TRADEMARK, README.md, package.json, and LICENSE to npm
  .npmignore
Labels: ergonomics, pr - good to merge

#285 Layer ordering
  package.json
  src/RenderWebGL.js
  src/playground/index.html
  src/util/log.js
Labels: pr - good to merge

#296 Remove duplicate xml escaping
  .eslintignore
  package.json
  src/util/svg-text-bubble.js
  src/util/svg-text-wrapper.js
  tap-snapshots/test-integration-scratch-tests.js-TAP.test.js
  test/integration/scratch-tests.js
Labels: pr - good to merge

#272 Use src/index for browser entry point
  package.json
  src/util/text-wrapper.js
  webpack.config.js
Labels: pr - needs work
