Repository LLK/scratch-render, pull requests merged in 2019-02, with the labels that each got.

#407 Adjust CPU isTouchingColor to match GPU results
  src/Drawable.js
  src/RenderWebGL.js
  src/Silhouette.js
Labels: pr - needs review

#408 Use Math.ceil and Math.floor to match Scratch 2 logic
  src/RenderWebGL.js
  test/integration/scratch-tests/sprite-goes-off-stage.sb2
Labels: compatibility, pr - needs review

#411 chore(package): update scratch-vm to version 0.2.0-prerelease.2019020…
  package.json
Labels: greenkeeper, pr - needs review

#409 Compatibility fix for bitmap position off stage
  src/BitmapSkin.js
  src/RenderWebGL.js
  src/Skin.js
  test/integration/scratch-tests/sprite-goes-off-stage.sb2
Labels: compatibility, pr - good to merge

#406 Add "query playground"
  src/RenderWebGL.js
  src/playground/.eslintrc.js
  src/playground/getMousePosition.js
  src/playground/index.html
  src/playground/playground.js
  src/playground/queryPlayground.html
  src/playground/queryPlayground.js
  webpack.config.js
Labels: pr - needs review
