Repository LLK/scratch-render, pull requests merged in 2019-01, with the labels that each got.

#385 Always use nearest for raster textures
  src/Drawable.js
Labels: pr - needs review

#392 Fix uncaught error `cannot find property updateSilhouette of null`
  src/RenderWebGL.js
Labels: critical, pr - good to merge

#391 Increase maximum texture size and back it off if GL fails to render
  src/SVGSkin.js
Labels: critical, pr - good to merge

#394 Implement updateSilhouette to allow updates to happen when needed
  src/SVGSkin.js
Labels: pr - good to merge

#399 Change brightness effect to match Scratch 2.0 in 2D mode
  src/shaders/sprite.frag
Labels: pr - good to merge

#402 Fix typo for sb3 test files
  test/integration/scratch-tests.js
Labels: bug, pr - good to merge

#376 Fix extraction of drawable to not clip bounds.
  src/RenderWebGL.js
Labels: pr - good to merge
