Repository LLK/scratch-render, pull requests merged in 2020-10, with the labels that each got.

#445 Cache and don't re-create transformed hull points
  src/Drawable.js
Labels: performance, pr - good to merge

#703 add hotfix capability to .travis.yml
  .travis.yml
Labels: pr - good to merge

#557 Clean up PenSkin code
  src/PenSkin.js
Labels: PRaparooza, pr - good to merge

#624 Move `updateCPURenderAttributes` calls to where they're actually needed
  src/RenderWebGL.js
Labels: pr - good to merge
